### ISSUE TITLE
log rotation for the logfile

### ISSUE THREAD

**Issue by gits7r** [spesmilo/electrum-server#95]
Been running electrum nodes with continuous uptime, I saw electrum.log (electrum server's log file) infinitely grows. Removing it entirely without keeping the last maybe let's say 100 lines might not be so healthy for debugging and server monitoring, in case something goes wrong or in case we need to identify a bug. Would be nice if we could have some kind of a log rotation, like Tor has, which sends a SIGHUP to the process and renames electrum.log to electrum.log.1 after a given time, and deletes .1 after some more time.

**Comment by ryanjohns** [comment]
I would recommend just using your system's regular log rotation functionality. I dropped the a file in my `/etc/logrotate.d/` directory with the following contents and it works well. Customize to your liking.

```
/path/to/electrum.log {
  rotate 5
  copytruncate
  daily
  missingok
  notifempty
  compress
  delaycompress
}
```

**Comment by gits7r** [comment]
Hey, thanks for the tip. It would be nice if electrum-server, when installed, would do this by default.

I have created a file called 'electrum' in /etc/logrotate.d with the contents you provided + create 0640 electrum adm. How do I activate it and enforce it? I have run $~: logrotate electrum, no console output put the logfile is still huge.

**Comment by ryanjohns** [comment]
Unless everyone installs electrum such that the log file is located at a common path, it is difficult to provide this automatically. I can't remember the installation process well enough since I did it so long ago to comment on the feasibility.

Usually log rotation runs via cron. Check out `/etc/cron.daily/logrotate` and see the man pages for how to run log rotation manually. You can also view the system crontab file if you're unsure when the daily cron jobs run.

```
cat /etc/cron.daily/logrotate
man logrotate
cat /etc/crontab
```

**Comment by ecdsa** [comment]
I agree; you should use logrotate
